global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'portalasig-ms-uaa'
    metrics_path: '/portalasig/uaa/actuator/prometheus'
    static_configs:
      - targets: ['host.gateway:5860'] #5860 is portalasig-ms-uaa port in local environment
